/// <autosync enabled="true" />
/// <reference path="bootstrap-datetimepicker.js" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery-2.1.1.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="moment-with-locales.js" />
/// <reference path="moment.js" />
/// <reference path="respond.js" />
/// <reference path="../content_admin panel/js/bootstrap.js" />
/// <reference path="../content_admin panel/js/jquery.js" />
/// <reference path="../index_files/vlb_engine/jquery.min.js" />
/// <reference path="../index_files/vlb_engine/visuallightbox.js" />
/// <reference path="../index_files/vlb_engine/vlbdata1.js" />
/// <reference path="../owl.carousel/owl-carousel/owl.carousel.js" />
/// <reference path="../images/index_files/vlb_engine/jquery.min.js" />
/// <reference path="../images/index_files/vlb_engine/visuallightbox.js" />
/// <reference path="../images/index_files/vlb_engine/vlbdata1.js" />
/// <reference path="../owl.carousel/assets/js/application.js" />
/// <reference path="../owl.carousel/assets/js/bootstrap-collapse.js" />
/// <reference path="../owl.carousel/assets/js/bootstrap-tab.js" />
/// <reference path="../owl.carousel/assets/js/bootstrap-transition.js" />
/// <reference path="../owl.carousel/assets/js/jquery-1.9.1.min.js" />
/// <reference path="../printarea-master/printarea-master/js/jquery.printarea.js" />
/// <reference path="../content_admin panel/js/plugins/flot/excanvas.min.js" />
/// <reference path="../content_admin panel/js/plugins/flot/flot-data.js" />
/// <reference path="../content_admin panel/js/plugins/flot/jquery.flot.js" />
/// <reference path="../content_admin panel/js/plugins/flot/jquery.flot.pie.js" />
/// <reference path="../content_admin panel/js/plugins/flot/jquery.flot.resize.js" />
/// <reference path="../content_admin panel/js/plugins/flot/jquery.flot.tooltip.min.js" />
/// <reference path="../content_admin panel/js/plugins/morris/morris-data.js" />
/// <reference path="../content_admin panel/js/plugins/morris/morris.js" />
/// <reference path="../content_admin panel/js/plugins/morris/raphael.min.js" />
/// <reference path="../owl.carousel/assets/js/google-code-prettify/prettify.js" />
/// <reference path="../owl.carousel/assets/js/google-code-prettify/run_prettify.js" />
